### ISSUE TITLE
Errors when running on PHP 8.1

### ISSUE THREAD

**Issue by davidcahlander** [goat1000/SVGGraph#62]
While porting my program to PHP 8.1 I got the errors:
[19-Jun-2022 17:04:55 America/Boise] PHP Warning:  A non-numeric value encountered in /home3/moudevor/public_html/SVGGraph/SVGGraphGridGraph.php on line 316
[19-Jun-2022 17:04:55 America/Boise] PHP Warning:  A non-numeric value encountered in /home3/moudevor/public_html/SVGGraph/SVGGraphGridGraph.php on line 316
[19-Jun-2022 17:04:55 America/Boise] PHP Warning:  A non-numeric value encountered in /home3/moudevor/public_html/SVGGraph/SVGGraphGridGraph.php on line 316
[19-Jun-2022 17:04:55 America/Boise] PHP Warning:  A non-numeric value encountered in /home3/moudevor/public_html/SVGGraph/SVGGraphGridGraph.php on line 316
[19-Jun-2022 17:04:55 America/Boise] PHP Warning:  A non-numeric value encountered in /home3/moudevor/public_html/SVGGraph/SVGGraphGridGraph.php on line 316
[19-Jun-2022 17:04:55 America/Boise] PHP Warning:  A non-numeric value encountered in /home3/moudevor/public_html/SVGGraph/SVGGraphGridGraph.php on line 316
[19-Jun-2022 17:04:55 America/Boise] PHP Fatal error:  Uncaught TypeError: Unsupported operand types: string * int in /home3/moudevor/public_html/SVGGraph/SVGGraphGuidelines.php:257
Stack trace:
#0 /home3/moudevor/public_html/SVGGraph/SVGGraphGuidelines.php(227): Guidelines->BuildGuideline(Array, '', '', Array, '')
#1 /home3/moudevor/public_html/SVGGraph/SVGGraphGuidelines.php(189): Guidelines->Get(0)
#2 /home3/moudevor/public_html/SVGGraph/SVGGraphGridGraph.php(2014): Guidelines->GetBelow()
#3 /home3/moudevor/public_html/SVGGraph/SVGGraphMultiLineGraph.php(34): GridGraph->UnderShapes()
#4 /home3/moudevor/public_html/SVGGraph/SVGGraph.php(401): MultiLineGraph->Draw()
#5 /home3/moudevor/public_html/SVGGraph/SVGGraph.php(1449): Graph->DrawGraph()
#6 /home3/moudevor/public_html/SVGGraph/SVGGraph.php(1488): Graph->BuildGraph()
#7 /home3/moudevor/public_html/SVGGraph/SVGGraph.php(181): Graph->Fetch('bar graph', true)
#8 /home3/moudevor/public_html/book/species_svg.php(530): SVGGraph->Fetch('MultiLineGraph', 'bar graph')
#9 /home3/moudevor/public_html/book/species_svg.php(267): draw_graph('Eastern Phoebe')
#10 {main}
  thrown in /home3/moudevor/public_html/SVGGraph/SVGGraphGuidelines.php on line 257
The program is at:
http://moudev.org/book/species_svg.php?species=Eastern%20Phoebe&width=660&height=280

I'm not sure all the changes have been made from the previous version (non-autoload).  The only thing changed was:
        $graph->colours() = array('blue','white');
to:
        $graph->colours(array('blue','white'));

**Comment by davidcahlander** [comment]
Please ignore the comment.  I was running the old library not the new library.
